name: Deploy to gh-pages

on:
  push:
    branches: [ main, revamp, revamp-deploy ]
  repository_dispatch:
    types: [ update ]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install requirements
        run: |
          cd new-website
          cd utils
          pip install -r requirements.txt

      - name: fetch latest deepchem version
        run: |
          cd new-website
          cd utils/home
          python3 fetch-version.py

      - name: fetch and convert model data
        run: |
          cd new-website
          cd utils/models
          python3 get_models.py

      - name: install and build
        run: |
          cd new-website
          cd deepchem
          npm i --legacy-peer-deps
          npm run lint
          npm run export

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: new-website/deepchem/out
          branch: gh-pages
          clean-exclude: |
            .nojekyll
            CNAME
            LICENSE
