name: Deploy to gh-pages

on:
  push:
    branches: [ main, revamp ]
  pull_request:
    branches: [ main, revamp ]
  repository_dispatch:
    types: [ update ]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v3

      - name: install and build
        run: |
          cd new-website
          cd deepchem
          npm i --legacy-peer-deps
          npm run lint
          npm run export

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: new-website/deepchem/out
          branch: gh-pages
          clean-exclude: |
            .nojekyll
            CNAME
            LICENSE